name: Malicious JS Checker

on:
  push:
    branches:
      - main

jobs:
  check_js_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Check for malicious JS files
        run: |
          for file in $(git diff --name-only HEAD^..HEAD); do
            if [[ $file == *.js ]]; then
              echo "Checking file $file for malicious code..."
              eslint $file
            fi
          done
