name: Integration Testing

on:
  pull_request:
    branches:
      - main
      - staging
      - development
  push:
    branches:
      - main
      - staging
      - development

jobs:
  test:
    name: Start Application Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Start Application
        run: |
          npm start & 
          echo "Waiting for the application to start..."
          wait-for-it -t 0 localhost:8000 -- echo "App is running"
