name: Quality Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install Node.js and npm
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run ESLint for linting
      - name: Run ESLint
        run: npm run lint

      # Run Prettier for code formatting
      - name: Run Prettier
        run: npm run format:check

      # Run dependency security scan
      - name: Run Dependency Security Check
        run: npm audit

      # Optionally, you can include other quality checks such as unit tests, type checking, etc.
